<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="K589LTRV" failures="0" tests="6" name="com.himalaya.tests.CartTest" time="1.638" errors="1" timestamp="2024-05-07T12:43:02 IST" skipped="4">
  <testcase classname="com.himalaya.tests.CartTest" name="checkTitle" time="0.823"/>
  <testcase classname="com.himalaya.tests.CartTest" name="emptyCart" time="0.814">
    <error message="Cannot invoke &quot;com.himalaya.pom.CartPOM.CartClick()&quot; because &quot;this.cart&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.himalaya.pom.CartPOM.CartClick()" because "this.cart" is null
at com.himalaya.tests.CartTest.emptyCart(CartTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- emptyCart -->
  <testcase classname="com.himalaya.tests.CartTest" name="ProductAdd" time="0.000">
    <skipped/>
  </testcase> <!-- ProductAdd -->
  <testcase classname="com.himalaya.tests.CartTest" name="checkcart" time="0.001">
    <skipped/>
  </testcase> <!-- checkcart -->
  <testcase classname="com.himalaya.tests.CartTest" name="checkSubmit" time="0.000">
    <skipped/>
  </testcase> <!-- checkSubmit -->
  <testcase classname="com.himalaya.tests.CartTest" name="removeProduct" time="0.000">
    <skipped/>
  </testcase> <!-- removeProduct -->
</testsuite> <!-- com.himalaya.tests.CartTest -->
